environment: 
  NLTK_PTB_DP_FILE: $PWD\nltk_data\corpora\dependency_treebank\nltk-ptb.dp 
  LIMA_DIST: $PWD\dist LIMA_CONF=$LIMA_DIST\share\config\lima
  LIMA_RESOURCES: $LIMA_DIST\share\apps\lima\resources 
  PATH: $LIMA_DIST\bin:$LIMA_DIST\share\apps\lima\scripts::$LIMA_DIST\lib:$PATH
  LIMA_DISABLE_FSW_TESTING: true 
  LIMA_DISABLE_CPACK_DEBIAN_PACKAGE_SHLIBDEPS=true 
  release: "`git show -s --format=%ct HEAD`-`git rev-parse --short HEAD`"

#install:
  #- python -m nltk.downloader -d nltk_data dependency_treebank
  #- cat nltk_data\corpora\dependency_treebank\wsj_*.dp | grep -v "^$" > nltk_data\corpora\dependency_treebank\nltk-ptb.dp

build_script:
  mkdir dist
  mkdir build
  cd build
  cmake -DLIMA_RESOURCES:STRING=build -DCMAKE_INSTALL_PREFIX:PATH=$ENV{LIMA_DIST} -DCMAKE_BUILD_TYPE:STRING=Release  -DLIMA_VERSION_RELEASE:STRING="master" ..
  nmake
  

