sudo: required

language: cpp
services:
  - docker

env:
  global:
    - secure: FlsmywHiGR6VKejCGcEd59rhvk5YI1f+FUAWfBLVxzqG4haLGT0MQwyxDr2EPS3Iu+v16nsMxHT2dwMCotC8zTPSmHUr6evE4jpNcqs+vIOAz7VLjdqwD0jweeguOR4JxL1XcgFZMAPTnoQFBFZlEOFu8OxaDjOoG7Oj0iGH+Fo=

before_install:
  - docker pull ubuntu:14.04 

script:
- docker build 
    --build-arg BINTRAYKEY=$BINTRAYKEY  
    --build-arg TRAVIS_JOB_NUMBER=$TRAVIS_JOB_NUMBER 
    --build-arg NLTK_PTB_DP_FILE=/nltk_data/corpora/dependency_treebank/nltk-ptb.dp
    --build-arg LIMA_DISABLE_FSW_TESTING=true
    --build-arg LIMA_DISABLE_CPACK_DEBIAN_PACKAGE_SHLIBDEPS=true
    -f ./Dockerfile-ubuntu14.04 .

