language: cpp
compiler: gcc
env: 
  global:
    - secure: FlsmywHiGR6VKejCGcEd59rhvk5YI1f+FUAWfBLVxzqG4haLGT0MQwyxDr2EPS3Iu+v16nsMxHT2dwMCotC8zTPSmHUr6evE4jpNcqs+vIOAz7VLjdqwD0jweeguOR4JxL1XcgFZMAPTnoQFBFZlEOFu8OxaDjOoG7Oj0iGH+Fo=
    - NLTK_PTB_DP_FILE=$PWD/nltk_data/corpora/dependency_treebank/nltk-ptb.dp LIMA_DIST=$PWD/dist LIMA_CONF=$LIMA_DIST/share/config/lima LIMA_RESOURCES=$LIMA_DIST/share/apps/lima/resources PATH=$LIMA_DIST/bin:$LIMA_DIST/share/apps/lima/scripts:$PATH LD_LIBRARY_PATH=$LIMA_DIST/lib    LIMA_DISABLE_FSW_TESTING=true LIMA_DISABLE_CPACK_DEBIAN_PACKAGE_SHLIBDEPS=true QT_BASE_DIR=/opt/qt53 QTDIR=$QT_BASE_DIR PATH=$QT_BASE_DIR/bin:$PATH LD_LIBRARY_PATH=$QT_BASE_DIR/lib/x86_64-linux-gnu:$QT_BASE_DIR/lib:$LD_LIBRARY_PATH PKG_CONFIG_PATH=$QT_BASE_DIR/lib/pkgconfig:$PKG_CONFIG_PATH  release="`git show -s --format=%ct HEAD`-`git rev-parse --short HEAD`"
install:
- cat /etc/*-release
- echo `echo 2 | sudo update-alternatives --config gcc`
- sudo add-apt-repository --yes ppa:kubuntu-ppa/backports
- sudo apt-get update
- sudo apt-get install -qq -y --force-yes cmake 
- sudo add-apt-repository --yes ppa:beineri/opt-qt532
- sudo apt-get update -qq
- sudo apt-get install -qq -y --force-yes qt53base  qt53tools
- sudo apt-get install -qq -y --force-yes libboost1.48-all-dev  libenchant-dev python-nltk gawk
- curl -sL https://deb.nodesource.com/setup | sudo bash -
- sudo apt-get install -y nodejs 
- sudo npm install -g json
- sudo sed -ie "s|DEFAULT_URL = 'http://nltk.googlecode.com/svn/trunk/nltk_data/index.xml'|DEFAULT_URL
  = 'http://nltk.github.com/nltk_data/'|" /usr/lib/python2.7/*/nltk/downloader.py
- python -m nltk.downloader -d nltk_data dependency_treebank
- cat nltk_data/corpora/dependency_treebank/wsj_*.dp | grep -v "^$" > nltk_data/corpora/dependency_treebank/nltk-ptb.dp
- export QHTTPSERVER_LATEST=`curl https://api.bintray.com/packages/kleag/ubuntu-12.04/qhttpserver | json -a latest_version`
- export QHTTPSERVER_LATEST_NAME=`curl https://api.bintray.com/packages/kleag/ubuntu-12.04/qhttpserver/versions/$QHTTPSERVER_LATEST/files | json 0.name`
- export QHTTPSERVER_LATEST_PATH=`curl https://api.bintray.com/packages/kleag/ubuntu-12.04/qhttpserver/versions/$QHTTPSERVER_LATEST/files | json 0.path`
- wget https://bintray.com/artifact/download/kleag/ubuntu/$QHTTPSERVER_LATEST_PATH
- sudo dpkg -i $QHTTPSERVER_LATEST_NAME
- export SVMTOOL_LATEST=`curl https://api.bintray.com/packages/kleag/ubuntu-12.04/svmtool-cpp | json -a latest_version`
- export SVMTOOL_LATEST_NAME=`curl https://api.bintray.com/packages/kleag/ubuntu-12.04/svmtool-cpp/versions/$SVMTOOL_LATEST/files | json 0.name`
- export SVMTOOL_LATEST_PATH=`curl https://api.bintray.com/packages/kleag/ubuntu-12.04/svmtool-cpp/versions/$SVMTOOL_LATEST/files | json 0.path`
- wget https://bintray.com/artifact/download/kleag/ubuntu-12.04/$SVMTOOL_LATEST_PATH
- sudo dpkg -i $SVMTOOL_LATEST_NAME
script: mkdir dist && mkdir build && cd build && cmake -DLIMA_RESOURCES:STRING=build
  -DCMAKE_INSTALL_PREFIX:PATH=$ENV{LIMA_DIST} -DCMAKE_BUILD_TYPE:STRING=Release  -DLIMA_VERSION_RELEASE:STRING="$release"
  .. && make -j4
after_success:
- pushd $LIMA_DIST/share/apps/lima/tests
- tva --language=eng test-eng.*.xml 2>&1 | tee tva-eng.log
- tva --language=fre test-fre.default.xml test-fre.disambiguated.xml test-fre.hyphen.xml
  test-fre.idiom.xml test-fre.sa.xml test-fre.se.xml test-fre.simpleword.xml test-fre.tokenizer.xml
  2>&1 | tee tva-fre.log
- curl -T /home/travis/build/aymara/lima/build/lima_common-prefix/src/lima_common-build/limacommon-2.1.$release-Linux.deb
  -ukleag:$BINTRAYKEY https://api.bintray.com/content/kleag/ubuntu-12.04/lima/$TRAVIS_JOB_NUMBER/$TRAVIS_JOB_NUMBER/limacommon-2.1.$release-Linux.deb
- curl -T /home/travis/build/aymara/lima/build/lima_linguisticprocessing-prefix/src/lima_linguisticprocessing-build/limalinguisticprocessing-2.1.$release-Linux.deb
  -ukleag:$BINTRAYKEY https://api.bintray.com/content/kleag/ubuntu-12.04/lima/$TRAVIS_JOB_NUMBER/$TRAVIS_JOB_NUMBER/limalinguisticprocessing-2.1.$release-Linux.deb
- curl -T /home/travis/build/aymara/lima/build/lima_linguisticdata-prefix/src/lima_linguisticdata-build/limalinguisticdata-2.1.$release-Linux.deb
  -ukleag:$BINTRAYKEY https://api.bintray.com/content/kleag/ubuntu-12.04/lima/$TRAVIS_JOB_NUMBER/$TRAVIS_JOB_NUMBER/limalinguisticdata-2.1.$release-Linux.deb
- curl -XPOST -ukleag:$BINTRAYKEY https://api.bintray.com/content/kleag/ubuntu-12.04/lima/$TRAVIS_JOB_NUMBER/publish
- curl -XGET https://bintray.com/kleag/ubuntu-12.04/lima/$TRAVIS_JOB_NUMBER


