sudo: required

language: cpp
services:
  - docker

env:
  global:
    - secure: FlsmywHiGR6VKejCGcEd59rhvk5YI1f+FUAWfBLVxzqG4haLGT0MQwyxDr2EPS3Iu+v16nsMxHT2dwMCotC8zTPSmHUr6evE4jpNcqs+vIOAz7VLjdqwD0jweeguOR4JxL1XcgFZMAPTnoQFBFZlEOFu8OxaDjOoG7Oj0iGH+Fo=

before_install:
  - docker pull ubuntu:14.04 

script:
- docker build 
    --build-arg BINTRAYKEY=$BINTRAYKEY  
    --build-arg JOB_NUMBER=$TRAVIS_JOB_NUMBER 
    -f ./Dockerfile-travis-ubuntu16.04 .

