sudo: required

language: cpp
services:
  - docker

env:
  global:
    - secure: FlsmywHiGR6VKejCGcEd59rhvk5YI1f+FUAWfBLVxzqG4haLGT0MQwyxDr2EPS3Iu+v16nsMxHT2dwMCotC8zTPSmHUr6evE4jpNcqs+vIOAz7VLjdqwD0jweeguOR4JxL1XcgFZMAPTnoQFBFZlEOFu8OxaDjOoG7Oj0iGH+Fo=
    - NLTK_PTB_DP_FILE=/nltk_data/corpora/dependency_treebank/nltk-ptb.dp LIMA_DIST=/src/lima/dist LIMA_CONF=$LIMA_DIST/share/config/lima LIMA_RESOURCES=$LIMA_DIST/share/apps/lima/resources PATH=$LIMA_DIST/bin:$LIMA_DIST/share/apps/lima/scripts:$PATH LD_LIBRARY_PATH=$LIMA_DIST/lib  LIMA_DISABLE_FSW_TESTING=true LIMA_DISABLE_CPACK_DEBIAN_PACKAGE_SHLIBDEPS=true  release="`git show -s --format=%ct HEAD`-`git rev-parse --short HEAD`"

before_install:
  - docker pull ubuntu:14.04 
  #- docker pull ubuntu:16.04 

script:
- docker build --build-arg BINTRAYKEY=$BINTRAYKEY  \
    --build-arg TRAVIS_JOB_NUMBER=$TRAVIS_JOB_NUMBER \
    --build-arg NLTK_PTB_DP_FILE= $NLTK_PTB_DP_FILE \
    --build-arg LIMA_DIST=$LIMA_DIST  \
    --build-arg LIMA_CONF=$LIMA_CONF  \
    --build-arg LIMA_RESOURCES=$LIMA_RESOURCES \
    --build-arg PATH=$PATH \
    --build-arg LD_LIBRARY_PATH=$LD_LIBRARY_PATH \
    --build-arg LIMA_DISABLE_FSW_TESTING=$LIMA_DISABLE_FSW_TESTING \
    --build-arg LIMA_DISABLE_CPACK_DEBIAN_PACKAGE_SHLIBDEPS=$LIMA_DISABLE_CPACK_DEBIAN_PACKAGE_SHLIBDEPS \
    --build-arg release=$release \
    -f ./Dockerfile-ubuntu16.04 .
- docker build \
    --build-arg BINTRAYKEY=$BINTRAYKEY  \
    --build-arg TRAVIS_JOB_NUMBER=$TRAVIS_JOB_NUMBER \
    --build-arg NLTK_PTB_DP_FILE= $NLTK_PTB_DP_FILE \
    --build-arg LIMA_DIST=$LIMA_DIST  \
    --build-arg LIMA_CONF=$LIMA_CONF  \
    --build-arg LIMA_RESOURCES=$LIMA_RESOURCES \
    --build-arg PATH=$PATH \
    --build-arg LD_LIBRARY_PATH=$LD_LIBRARY_PATH \
    --build-arg LIMA_DISABLE_FSW_TESTING=$LIMA_DISABLE_FSW_TESTING \
    --build-arg LIMA_DISABLE_CPACK_DEBIAN_PACKAGE_SHLIBDEPS=$LIMA_DISABLE_CPACK_DEBIAN_PACKAGE_SHLIBDEPS \
    --build-arg release=$release \
    -f ./Dockerfile-ubuntu14.04 .

