init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

environment: 
  NLTK_PTB_DP_FILE: c:\dependency_treebank\nltk-ptb.dp 
  LIMA_DIST: c:\d 
  LIMA_CONF: 'c:\d\share\config\lima'
  LIMA_RESOURCES: 'c:\d\share\apps\lima\resources' 
  QTDIR: 'C:\Qt\5.5\msvc2013_64'
  BOOST_ROOT: 'C:\Libraries\boost'
  BOOST_LIBRARYDIR: 'C:\Libraries\boost\lib64-msvc-12.0'
  PATH: '%QTDIR%\bin;c:\d\bin;c:\d\share\apps\lima\scripts;c:\d\lib;%BOOST_LIBRARYDIR%;%PATH%'
  LIMA_DISABLE_FSW_TESTING: true 
  NLTK_PTB_DP_DIR: 'c:\dependency_treebank'

os: Visual Studio 2013

install:
  - ps: (new-object net.webclient).DownloadFile('http://www.nltk.org/nltk_data/packages/corpora/dependency_treebank.zip', 'c:\dependency_treebank.zip')
  - mkdir c:\dependency_treebank
  - ps: unzip c:\dependency_treebank.zip -d c:\
  - cd c:\
  - cat c:\dependency_treebank\wsj_*.dp | grep -v "^$" > c:\dependency_treebank\nltk-ptb.dp

build_script:
  - mkdir c:\b
  - cd c:\b
  - cmake -G "Visual Studio 12 2013 Win64" "-DCMAKE_PREFIX_PATH=%QTDIR%" "-DLIMA_RESOURCES=build" "-DCMAKE_BUILD_TYPE=Release" c:/projects/lima 
  - cmake --build . --config Release  
  #- tva --language=fre test-fre.default.xml test-fre.disambiguated.xml test-fre.hyphen.xml test-fre.idiom.xml test-fre.sa.xml test-fre.se.xml test-fre.simpleword.xml test-fre.tokenizer.xml

on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
