environment: 
  NLTK_PTB_DP_FILE: c:\projects\lima\nltk_data\corpora\dependency_treebank\nltk-ptb.dp 
  LIMA_DIST: c:\projects\lima\dist 
  LIMA_CONF: '%LIMA_DIST%\share\config\lima'
  LIMA_RESOURCES: '%LIMA_DIST%\share\apps\lima\resources' 
  QTDIR: 'C:\Qt\5.5\msvc2013_64'
  PATH: '%QTDIR%\bin;%LIMA_DIST%\bin;%LIMA_DIST%\share\apps\lima\scripts%LIMA_DIST%\lib;%PATH%'
  LIMA_DISABLE_FSW_TESTING: true 

os: Visual Studio 2013

#install:
  #- python -m nltk.downloader -d nltk_data dependency_treebank
  #- cat nltk_data\corpora\dependency_treebank\wsj_*.dp | grep -v "^$" > nltk_data\corpora\dependency_treebank\nltk-ptb.dp

build_script:
  - mkdir build
  - cd build
  - dir C:\Libraries\boost_1_59_0\boost
  - cmake ../ -G "Visual Studio 12 2013 Win64" "-DCMAKE_PREFIX_PATH=%QTDIR%" -DBOOST_ROOT=C:/Libraries/boost_1_59_0 -DBoost_INCLUDE_DIR=C:/Libraries/boost_1_59_0
  - cmake --build . --config Release  

