init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

environment: 
  NLTK_PTB_DP_FILE: c:\projects\lima\nltk_data\corpora\dependency_treebank\nltk-ptb.dp 
  LIMA_DIST: c:\d 
  LIMA_CONF: '%LIMA_DIST%\share\config\lima'
  LIMA_RESOURCES: '%LIMA_DIST%\share\apps\lima\resources' 
  QTDIR: 'C:\Qt\5.5\msvc2013_64'
  BOOST_ROOT: 'C:\Libraries\boost'
  BOOST_LIBRARYDIR: 'C:\Libraries\boost\lib64-msvc-12.0'
  PATH: '%QTDIR%\bin;%LIMA_DIST%\bin;%LIMA_DIST%\share\apps\lima\scripts;%LIMA_DIST%\lib;%BOOST_LIBRARYDIR%;%PATH%'
  LIMA_DISABLE_FSW_TESTING: true 

os: Visual Studio 2013

#install:
  #- python -m nltk.downloader -d nltk_data dependency_treebank
  #- cat nltk_data\corpora\dependency_treebank\wsj_*.dp | grep -v "^$" > nltk_data\corpora\dependency_treebank\nltk-ptb.dp

build_script:
  - mkdir c:\b
  - cd c:\b
  - cmake -G "Visual Studio 12 2013 Win64" "-DCMAKE_PREFIX_PATH=%QTDIR%" c:/projects/lima
  - cmake --build . --config Release  
  - tva --language=fre test-fre.default.xml test-fre.disambiguated.xml test-fre.hyphen.xml test-fre.idiom.xml test-fre.sa.xml test-fre.se.xml test-fre.simpleword.xml test-fre.tokenizer.xml

on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
