environment: 
  NLTK_PTB_DP_FILE: c:\projects\lima\nltk_data\corpora\dependency_treebank\nltk-ptb.dp 
  LIMA_DIST: c:\projects\lima\dist 
  LIMA_CONF: '%LIMA_DIST%\share\config\lima'
  LIMA_RESOURCES: '%LIMA_DIST%\share\apps\lima\resources' 
  PATH: '%LIMA_DIST%\bin;%LIMA_DIST%\share\apps\lima\scripts%LIMA_DIST%\lib;%PATH%'
  PATH: 'C:\Qt\5.5\msvc2010_64\bin;%PATH%'
  LIMA_DISABLE_FSW_TESTING: true 
  QTDIR: 'C:\Qt\5.5\msvc2010_64'

#install:
  #- python -m nltk.downloader -d nltk_data dependency_treebank
  #- cat nltk_data\corpora\dependency_treebank\wsj_*.dp | grep -v "^$" > nltk_data\corpora\dependency_treebank\nltk-ptb.dp

build_script:
  - mkdir build
  - cd build
  - cmake ../ -G "Visual Studio 10 Win64"
  - cmake --build . --config Release  

